# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: posts
    url: /
    weight: 10
  - name: etiquetas
    url: tags/
    weight: 20
  - name: sobre mí
    url: uses/
    weight: 35
