# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Principal
    url: /
    weight: 10
  - name: Lastly
    url: tags/
    weight: 20
  - name: Currently
    url: uses/
    weight: 30
